version: "3"
services:
  main-db:
    image: "postgres:14"
    container_name: "fp-ms-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fp_ms_dev
    volumes:
      - /var/lib/postgresql/data
