addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"       % "2.0.8")
addSbtPlugin("com.github.sbt"      % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.3.1")
addSbtPlugin("com.github.geirolz"  % "sbt-service-info"    % "0.0.1")
