###################### APP ######################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    name: $APP_NAME
spec:
  selector:
    matchLabels:
      name: $APP_NAME
  template:
    metadata:
      labels:
        name: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $APP_DOCKER_IMAGE_NAME
          imagePullPolicy: Never
          ports:
            - containerPort: $APP_PORT
          envFrom:
            - secretRef:
                name: $SECRET_NAME
            - configMapRef:
                name: $CONFIGMAP_NAME
          readinessProbe:
            httpGet:
              path: $APP_HEALTHCHECK_PATH
              port: $APP_PORT
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: $APP_HEALTHCHECK_PATH
              port: $APP_PORT
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  selector:
    app.kubernetes.io/name: $APP_NAME
  ports:
    - protocol: TCP
      port: $APP_PORT
      targetPort: $APP_PORT

###################### CONFIG ######################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: $CONFIGMAP_NAME
data:
  MAIN_DB_NAME: "fp_ms_dev"
  MAIN_DB_HOST: ${DB_SERVICE_NAME}:${DB_SERVICE_TARGET_PORT}

---
apiVersion: v1
kind: Secret
metadata:
  name: $SECRET_NAME
type: Opaque
data:
  MAIN_DB_USERNAME: postgres
  MAIN_DB_PASSWORD: postgres

###################### DB ######################
---
apiVersion: v1
kind: Service
metadata:
  name: $DB_SERVICE_NAME
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: $APP_NAME
  ports:
    - name: http
      protocol: TCP
      port: $DB_SERVICE_TARGET_PORT
      targetPort: $DB_SERVICE_TARGET_PORT
  externalIPs:
    - $DB_SERVICE_TARGET_ADDRESS

#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: $DB_SERVICE_NAME
#subsets:
#  - addresses:
#      - ip: $DB_SERVICE_TARGET_ADDRESS
#    ports:
#      - port: $DB_SERVICE_TARGET_PORT
#        name: $DB_SERVICE_NAME
