name: CICD

# triggers
on:
  push:
    branches: ['*']
  release:
    types: [ created ]
  pull_request:
    branches:
      - main

# env variables
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

# jobs
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # supported scala versions
        scala:
          - 2.13.10

    steps:
      - uses: actions/checkout@v3

      #----------- JDK -----------
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "liberica"
          java-version: 17

      #----------- CACHE -----------
      - name: Cache SBT
        uses: actions/cache@v3.2.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.ivy2/cache
            ~/.sbt
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-sbt-${{ matrix.scala }}-${{ hashFiles('**/build.sb') }}

      #----------- COMPILE -----------
      - name: Compile, Format, Test and Coverage for ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean scalafmtCheck coverage test coverageReport

      #----------- COVERAGE -----------
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
